# Generated by Django 3.0.3 on 2020-02-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venuez', '0002_auto_20200204_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='booking',
        ),
    ]
