# Generated by Django 3.0.3 on 2020-02-11 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venuez', '0003_remove_rating_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue_img',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venuez.Venue'),
        ),
    ]
