# Generated by Django 3.0.3 on 2020-02-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuez', '0004_auto_20200211_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paci_no',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
