# Generated by Django 3.0.3 on 2020-02-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venuez', '0005_auto_20200211_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
